name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install SQLite3
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      - name: Create migration directories
        run: |
          mkdir -p db/migrate
          mkdir -p db/cache_migrate
          mkdir -p db/queue_migrate
          mkdir -p db/cable_migrate
      
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:test:prepare
          bundle exec rails db:schema:load
          bundle exec rails db:migrate
          bundle exec rails db:migrate:cache
          bundle exec rails db:migrate:queue
          bundle exec rails db:migrate:cable
      
      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test
      
      - name: Run security checks
        run: |
          bundle exec brakeman -q -w2
      
      - name: Run linting
        run: |
          bundle exec rubocop
